name = "Create: Beautiful Railways"
author = "KodiiTulip"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9c861ca8ba4e181615149ca406d9d3c2a2521d882d1e7c8bab7875381ae883"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
