name = "Create: Beautiful Railways"
author = "KodiiTulip"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c3ee177acfc8793952968bc21f6a5c721f255ea73ed6a15850ae99db04fa00"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
